//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StopWatch.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StopWatch.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your feedback is important! Rate Stopwatch 5 stars to add Countdown functionality. Proceed?.
        /// </summary>
        public static string AddCountdownQuestion {
            get {
                return ResourceManager.GetString("AddCountdownQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Laps.
        /// </summary>
        public static string AppBarClearLapsButton {
            get {
                return ResourceManager.GetString("AppBarClearLapsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string AppBarEmailButton {
            get {
                return ResourceManager.GetString("AppBarEmailButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best Stop Watch in the Windows Phone Store!
        ///
        ///Features include:
        ///
        ///* Email Lap and Split Times
        ///* Running under Lock Screen
        ///* Disable Lock Screen
        ///* Both Split and Total Time
        ///* Large, easy to read clock
        ///* Landscape support for big numbers
        ///
        ///Download this app today!.
        /// </summary>
        public static string AppDescription {
            get {
                return ResourceManager.GetString("AppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StopWatch.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AppMenuItemAbout {
            get {
                return ResourceManager.GetString("AppMenuItemAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Countdown.
        /// </summary>
        public static string AppMenuItemAddCountdown {
            get {
                return ResourceManager.GetString("AppMenuItemAddCountdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Apps.
        /// </summary>
        public static string AppMenuItemMoreApps {
            get {
                return ResourceManager.GetString("AppMenuItemMoreApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string AppMenuItemOptions {
            get {
                return ResourceManager.GetString("AppMenuItemOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Advertising.
        /// </summary>
        public static string AppMenuItemRemoveAdvertising {
            get {
                return ResourceManager.GetString("AppMenuItemRemoveAdvertising", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review.
        /// </summary>
        public static string AppMenuItemReview {
            get {
                return ResourceManager.GetString("AppMenuItemReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elapsed.
        /// </summary>
        public static string ColumnHeader1 {
            get {
                return ResourceManager.GetString("ColumnHeader1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split.
        /// </summary>
        public static string ColumnHeader2 {
            get {
                return ResourceManager.GetString("ColumnHeader2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countdown Alarm.
        /// </summary>
        public static string CountdownAlarm {
            get {
                return ResourceManager.GetString("CountdownAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countdown Finished!.
        /// </summary>
        public static string CountdownFinished {
            get {
                return ResourceManager.GetString("CountdownFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countdown Options.
        /// </summary>
        public static string CountdownOptions {
            get {
                return ResourceManager.GetString("CountdownOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Countdown Time.
        /// </summary>
        public static string DefaultCountdownTime {
            get {
                return ResourceManager.GetString("DefaultCountdownTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete all lap data?.
        /// </summary>
        public static string DeleteAllLapDataMessage {
            get {
                return ResourceManager.GetString("DeleteAllLapDataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Laps.
        /// </summary>
        public static string DeleteLapsTitle {
            get {
                return ResourceManager.GetString("DeleteLapsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number/Split/Lap.
        /// </summary>
        public static string EmailBody {
            get {
                return ResourceManager.GetString("EmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer Data.
        /// </summary>
        public static string EmailSubject {
            get {
                return ResourceManager.GetString("EmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exceed.
        /// </summary>
        public static string ExceedText {
            get {
                return ResourceManager.GetString("ExceedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StopWatch.
        /// </summary>
        public static string Keyword1 {
            get {
                return ResourceManager.GetString("Keyword1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer.
        /// </summary>
        public static string Keyword2 {
            get {
                return ResourceManager.GetString("Keyword2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sex.
        /// </summary>
        public static string Keyword3 {
            get {
                return ResourceManager.GetString("Keyword3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook.
        /// </summary>
        public static string Keyword4 {
            get {
                return ResourceManager.GetString("Keyword4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter.
        /// </summary>
        public static string Keyword5 {
            get {
                return ResourceManager.GetString("Keyword5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lap.
        /// </summary>
        public static string LapText {
            get {
                return ResourceManager.GetString("LapText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock Screen.
        /// </summary>
        public static string LockScreen {
            get {
                return ResourceManager.GetString("LockScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max time exceeded..
        /// </summary>
        public static string MaxTimeExceededMessage {
            get {
                return ResourceManager.GetString("MaxTimeExceededMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string PauseText {
            get {
                return ResourceManager.GetString("PauseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        public static string RateAppHeader {
            get {
                return ResourceManager.GetString("RateAppHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your feedback is very important to us! Please share your feedback with us by rating the StopWatch on the marketplace..
        /// </summary>
        public static string RateTheAppPrompt {
            get {
                return ResourceManager.GetString("RateTheAppPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your feedback is very important to us! Woud you like to share your feedback with us by rating the StopWatch on the marketplace?.
        /// </summary>
        public static string RateTheAppQuestion {
            get {
                return ResourceManager.GetString("RateTheAppQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record.
        /// </summary>
        public static string Record {
            get {
                return ResourceManager.GetString("Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate Stopwatch 5 stars to remove advertising. Proceed?.
        /// </summary>
        public static string RemoveAdvertisingQuestion {
            get {
                return ResourceManager.GetString("RemoveAdvertisingQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resetting with erase all lap data.  Proceed?.
        /// </summary>
        public static string ResetMessage {
            get {
                return ResourceManager.GetString("ResetMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string ResetText {
            get {
                return ResourceManager.GetString("ResetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        public static string ResumeText {
            get {
                return ResourceManager.GetString("ResumeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string StartText {
            get {
                return ResourceManager.GetString("StartText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StopWatch Options.
        /// </summary>
        public static string StopWatchOptions {
            get {
                return ResourceManager.GetString("StopWatchOptions", resourceCulture);
            }
        }
    }
}
